### ISSUE TITLE
Basic tests

### ISSUE THREAD

**Issue by cosme12** [cosme12/cheatsheet-maker#9]
Tests should be added. I will need help with this.

**Comment by janga1997** [comment]
@cosme12 I would like to work with you. What should we get started on?

**Comment by cosme12** [comment]
Cool @janga1997 I dont know how much experience you have with python, but if you are new, the easiest way to start is to improve #6 . If you have much more experience, you could build the unittest to verify every method.
I'm pushing every change to the Developer branch. Once we reach the new version milestone, I create a release branch where we test everything and then push it to master.
